adobe/aio-lib-runtime

src/triggers.js
Feed update does not work if the feed is not already present and create fails if it's already there.
So we are deleting it and ignoring the error if any.
=> fix: feed cleanup before creating

src/build-actions.js, src/deploy-actions.js, src/undeploy-actions.js, src/utils.js, test/build.actions.test.js, test/deploy.actions.test.js, test/utils.test.js
Fixes https://github.com/adobe/aio-cli-plugin-app/issues/276
- Adding support for multiple packages in app manifest.
- Backward compatibility is maintained for deploying specific actions instead of the whole manifest.
- `aio app deploy --action hello` will still deploy just the `hello` action in the default/first package.
- To deploy actions from custom user defined packages, use `aio app deploy --action <packageName>/hello`
=> Support for multiple packages in app manifest

src/build-actions.js, test/__fixtures__/custom-webpack/actions/actionname/action.js, test/__fixtures__/custom-webpack/manifest.yml, test/__fixtures__/named-package/actions/action-zip/package.json, test/__fixtures__/named-package/package.json, test/__fixtures__/sample-app-includes/actions/mock.config.js, test/__fixtures__/sample-app/actions/action-zip/package.json, test/build.actions.test.js
Configurable webpack 
- re-added implementation, tests, and fixtures
- replaces, closes #19
Search action path for `*webpack-config.js`
search order is:
1. /app-root/actions/actionname/
1. /app-root/actions/
1. /app-root/
Merge webpack config to include required props :
- entry [actionPath, ...]
- output { path, filename, ... }
- resolve.extensions [.js, .json, ... ]
- resolve.mainFields [ main, ... ]
- adobe/aio-cli-plugin-app/issues/344
- #30 
- adobe/aio-cli-plugin-app/issues/196
extensible everything
=> Configurable webpack - rebase

src/utils.js, test/__fixtures__/deploy/pkgparam_manifest_res.json, test/__fixtures__/deploy/pkgparam_manifest_res_multi.json, test/utils.test.js
Adding support for package parameters to be defined in the manifest using `inputs` .
```
packages:
mypkg:
license: Apache-2.0
inputs:
pkgparam1: 'pkgParam1Value'
actions:
myaction1:
function: actions/hello/index.js
runtime: 'nodejs:12'
web: true
annotations:
require-adobe-auth: false
```
These parameters will be automatically available for any actions within the package.
Fixes https://github.com/adobe/aio-cli-plugin-runtime/issues/200
=> feat: Support for package params in manifest

src/utils.js, test/print.action.logs.test.js, types.d.ts
Factors the activation banner printing into a function that can be overriden.
See https://github.com/adobe/aio-lib-runtime/issues/27.
This refactoring is semantic preserving but provides flexibility for downstream plugins to provide their own banner implementation.
=> Allow for external log banners.

src/build-actions.js
This pr shows how we can have a stage env value populated all the way through to the action.
Note that the value used are negotiable, I used process.env.AIO_ENV_IS_STAGE as it is a simple boolean value, and we only ever care if we are in stage or not, we don't care what allowed values for env might exist, or what the actual string value is ... just as simple, logical yes or no ...
[ACNA-1094], [ACNA-1095], [ACNA-1096]
tvm client needs to know which url to load, is it stage or prod ?
file-lib, state-lib might also need this info ...
I added this to an acton I was deploying:
console.log('AIO_ENV_IS_STAGE=', process.env.AIO_ENV_IS_STAGE)
and put a webpack-config in my action folder ( this requires that the project install webpack as a dependency )
```
const webpack = require('webpack') …
```
=> populate runtime action process.env value from local process.env value

.github/workflows/version-bump-publish.yml
This is required in cases of npm publish failure due to external reasons.
Same change goes for all our repos and probably https://github.com/adobe/.github/blob/main/workflow-templates/version-bump-publish.yml too.
=> Publish to NPM without bumping the version

src/utils.js, test/utils.test.js
Added support for nested input parameters.
Better support for env var replacement of manifest.yml keys.
https://github.com/adobe/aio-cli-plugin-runtime/issues/251
https://github.com/adobe/aio-cli-plugin-app/issues/299
Manually & Unit Testing.
=> Fix: [ACNA-1374]/[ACNA-936] Support for nested input parameters and full env var replacement. 

README.md, src/LogForwarding.js, src/LogForwardingLocalDestinationsProvider.js, src/RuntimeAPI.js, test/LogForwarding.test.js, test/LogForwardingUnderscoreNamespace.test.js, types.d.ts
This allows to set supported log forwarding settings in a single place (currently, it's `src/LogForwardingLocalDestinationsProvider.js`, in the future this can be fetched from Runtime API as such endpoint gets supported). This allows to keep Runtime library and Runtime aio plugin flexible enough to support any new destinations w/o modifying multiple places.
The task is done in scope of https://github.com/adobe/aio-cli-plugin-app/issues/501 with a reason to avoid modification of 3 places (https://github.com/adobe/aio-lib-runtime, https://github.com/adobe/aio-cli-plugin-runtime, https://github.com/adobe/aio-cli-plugin-app) as destination settings change, and instead limit changes to this repository.
Note: non-interactive commands in https://github.com/adobe/aio-cli-plugin-runtime still …
=> Generic API for Log Forwarding Configuration

src/LogForwarding.js, test/LogForwarding.test.js
Fixed an error with API and dependent `aio rt log-forwarding` commands in case OW api host doesn't contain protocol.
https://github.com/adobe/aio-lib-runtime/issues/89
Fix an issue.
Automated and manual testing.
=> Fixed: log forwarding API requests fails with no protocol in OpenWhisk apihost

src/LogForwarding.js, test/LogForwarding.test.js
Updated `set` API to return result from Runtime API as JSON.
Updated `errors` API to just return the server response.
Runtime API for Log Forwarding `PUT` was updated to return actual settings that were stored on the server. The response is JSON. Updated the SDK to reflect this and return JSON instead of text.
Required for
- https://github.com/adobe/aio-cli-plugin-app/issues/501
- https://github.com/adobe/aio-cli-plugin-runtime/issues/256
Manual and auto tests.
This changes return result of the Log Forwarding API.
=> Log Forwarding Set API Returns JSON instead of Text

src/utils.js, test/utils.test.js
The manifest spec limits keys we are supporting are:  
- timeout
- memorySize
- logSize
- concurrentActivations
This PR maps, concurrentActivations key to concurrency key. 
https://github.com/adobe/aio-cli-plugin-app/issues/507
unit tests
replication steps from the mentioned issue.
=> fix: ACNA-1480 - support for concurrentActivations limit key

src/utils.js, test/utils.test.js
The error only occurs on an invalid action runtime kind (e.g. `nodejs:8`) specified in the manifest, with v4.2.0, because of a null apihost.
To get a definitive apihost, we need to use the `initOptions` property of the Openwhisk object that is passed around: https://github.com/adobe/aio-lib-runtime/blob/30fdb960c6cc35fb22d8559a3ebbc6f35efaf6e6/src/RuntimeAPI.js#L90
Exception in the error message:
```
❯ aio app deploy
✔ Built 1 action(s) for 'dx/excshell/1'
✔ Building web assets for 'dx/excshell/1'
✖ Deploying actions for 'dx/excshell/1'
›   Error: Only absolute URLs are supported
```
1. npm test
2. npm link this branch into @adobe/aio-cli-plugin-app repo folder
3. `aio plugins link` the repo from step 2. above
4. in your project, modify an action to have `nodejs:8` as a kind in the …
=> fix: on unsupported runtime kind - apihost is null for deployPackage when validating the action runtime

src/build-actions.js, test/build.actions.test.js
This pull request proposes adding support for additional Webpack configuration types such as functions, arrays, and promises. 
This pull request adds support for the following Webpack configuration types: 
* Function that returns an object
* Function that returns an array of objects 
* Async function that returns an object
* Async function that returns an array of objects 
* Array of objects
* Array of functions that return objects
* Array of async functions that return objects 
Closes https://github.com/adobe/aio-lib-runtime/issues/36
Test ran locally using `npm run test`.
=> Add support for additional Webpack configuration types

src/utils.js, test/utils.test.js
Adobe Documentation state that memory limits should be configured as follow in the `app.config.yaml`
```
application:
actions: actions
web: web-src
runtimeManifest:
packages:
mypackage:
actions:
myactions:
function: actions/myaction.js
runtime: 'nodejs:14'
limits:
memory: 512
```
Currently the code only looks for property `memorySize` and not `memory`
[Documentation 1](https://developer.adobe.com/app-builder/docs/guides/appbuilder-configuration/#runtime-manifest)
[Documentation 2](https://developer.adobe.com/runtime/docs/guides/using/system_settings/)
#105 
The behaviour difference has been found by a customer here : https://experienceleaguecommunities.adobe.com/t5/project-firefly-questions/can-t-change-action-memory-limit/td-p/454197
- Automated tests
=> Memory limits follow documentation

e2e/e2e.js
- Improve e2e tests especially if there was a failure (on delete), by randomizing trigger names.
- added test for `/whisk.system/alarm/once`
npm run e2e
=> fix: update e2e tests for triggers, trigger with feed (unique names)

README.md, docs/readme_template.md, src/RuntimeAPI.js, test/index.test.js, types.d.ts
=> feat: ACNA-1962 - support node environment variable NODE_TLS_REJECT_UNAUTHORIZED=0

.eslintrc.json, package.json, src/utils.js, test/utils.test.js
This makes the lib a little more future-proof, instead of being forced to update our allowed kinds every time the server does, we allow some drift by asking the server directly.
=> Unlock client from server supported kinds

src/utils.js, test/utils.test.js
old regex: https://regex101.com/r/sBfXak/1
new regex: https://regex101.com/r/dOa3sT/1
Closes #139 
- Replaced `\w+` with `[a-zA-Z0-9_-]+`  (`\w` is equivalent to `[a-zA-Z0-9_]`)
- This can be `[\w-]+` as well, but I wanted to be explicit.
- npm test
=> fix: env vars with hyphens are not processed properly

src/utils.js
This adds 'connection: keep-alive' to every call to update package|action|rule|trigger.
This addresses an issue where the default values of headers 'connection: close' causes lengthy deploy operations to hang/fail in some environments.
This value is picked up by openwhisk-client-js, and passed through to needle.  No deeper change is required, although we will still be looking to move openwhisk-client-js to a newer release of needle which has some other fixes.
Manual testing.
=> Send connection: keep-alive 

src/deploy-actions.js, src/utils.js, test/utils.test.js
fix for #166. This code can be safely deleted now, it was kept as a strategy to rollback to the headless-v1 validator in 2021 see https://github.com/adobe/aio-lib-runtime/pull/65
=> Fix: stop setting ims org to state lib for dead validator

src/utils.js, test/utils.test.js
Note that due to https://github.com/adobe/aio-lib-runtime/pull/138 we do a server check, and since the server as of now supports `nodejs:20`, `nodejs:10`, and `nodejs:12`, it will not error out but will debug log a mismatch (instead of throwing an exception - this is so the client code is not the gatekeeper).
note: node-10 and node-12 will still be supported and will be removed at a later date according to our deprecation roadmap.
- npm test
- manual tests pending
=> feat: support nodejs:20 kind

src/utils.js
- When deploying actions, `aio` checks whether kind is supported by cli, and if not double-checks via the API [1].
- Even when blackboxes are enabled, `aio` prevents deployment because blackbox is not returned in supported kinds.
- We fix this by adding blackbox kind `SupportedRuntimes`
[1]
https://github.com/adobe/aio-lib-runtime/blob/e8815561e7d7e06e75e8f4d8cc6ef69da12fb7d2/src/utils.js#L1494
adobe/aio-cli-plugin-app#740
I originally opened adobe/aio-cli-plugin-app#739 but this change seems more correct.
I was developing a blackbox image locally before I had access to feature. Each time the actions are redeployed on code change I also have to rerun `wsk action update ... --docker ...` to update the container, but this seams unnecessary as the manifest already supports this.
Same issue …
=> Enable deployment of blackboxes via docker manifest property

.github/workflows/daily.yml, .github/workflows/node.js.yml, .github/workflows/on-push-publish-to-npm.yml, .github/workflows/prerelease.yml, .github/workflows/version-bump-publish.yml, package.json, test/__mocks__/fs-extra.js, test/__mocks__/fs.js, test/__mocks__/fs/promises.js, test/jest.setup.js
=> fix(breaking-change): update for nodes 18 and 20

e2e/e2e.js, e2e/jest.setup.js, src/utils.js, test/__fixtures__/custom-webpack/manifest.yml, test/__fixtures__/named-package/manifest.yml, test/__fixtures__/sample-app-includes/manifest.yml, test/__fixtures__/sample-app-reduced/manifest.yml, test/deploy.actions.test.js, test/jest.setup.js, test/utils.test.js
- fixes #172 
- removed all `nodejs:12` references (changed to `nodejs:18`)
- moved e2e tests into `describe` blocks
- npm run e2e
=> fix: ACNA-2738 - failing e2e tests because of mocked fs

src/build-actions.js, test/build.actions.test.js
We need a way to build actions in an app, without wiping out all the contents of the `dist` folder.
This is to facilitate fast turnaround time for action editing and debugging using the [dev plugin](https://github.com/adobe/aio-cli-plugin-app-dev). If not, we would have to build all the actions everytime one action is built, which increases latency.
Adding a new param, so it doesn't break existing users since the default value for `emptyDist` will be `true`.
https://github.com/adobe/aio-cli-plugin-app-dev/pull/87
- npm test
=> feat: add emptyDist param to buildActions

README.md, docs/readme_template.md, jest.config.js, package.json, src/deploy-actions.js, src/utils.js, test/__fixtures__/deploy/basic_manifest.json, test/utils.test.js, types.d.ts
Part of a fix in aio-cli-plugin-app. See https://github.com/adobe/aio-cli-plugin-app/issues/823
Blocks https://github.com/adobe/aio-cli-plugin-app/pull/824
- npm test
=> fix: ACNA-3397 - web action does not have web in the url, resulting in an invalid link

package.json, src/build-actions.js, test/__mocks__/dependency-tree.js, test/__mocks__/folder-hash.js, test/build.actions.test.js
This pr adds dependent files to the hash it generates during build.  Note that these files are still not watched, but if they change between run/dev/build it is detected.
=> fix: ACNA-3239 - hash dependencies not in node_modules

src/build-actions.js, test/build.actions.test.js
Support .cjs extensions for `webpack-config` file resolution
I understand that full support for es modules is not here yet, however, with this small change we can allow devs to build their apps with es modules while hooking in webpack as a commonJs module in the same repo.
=> Support .cjs extension for webpack config

src/build-actions.js, test/build.actions.test.js
Fixes #210 
On Windows only, when trying to use a custom webpack config per: https://developer.adobe.com/app-builder/docs/guides/configuration/webpack-configuration, the config is never loaded.
This PR fixes that by providing `globby`, the library used to resolve the config, with a POSIX path instead of a windows path. Per [globby docs](https://github.com/sindresorhus/globby/blob/main/readme.md#api)
>Note that glob patterns can only contain forward-slashes, not backward-slashes, so if you want to construct a glob pattern from path components, you need to use path.posix.join() instead of path.join().
tested it locally on my project on windows
- [ x] Bug fix (non-breaking change which fixes an issue)
=> fix: use posix paths with globby regardless of platform

src/LogForwarding.js, src/RuntimeAPI.js, test/LogForwarding.test.js
fixes #211 
- in a locally linked app plugin, `npm i github:adobe/aio-lib-runtime#story/ACNA-3770`
- in an AB project, run `aio app config set lf`
- if env var `IS_DEPLOY_SERVICE_ENABLED` is set to true, the fetch call should have the bearer token header
=> fix: log forwarding does not take into account auth_handler Openwhisk option

src/deploy-actions.js, src/utils.js, test/jest.setup.js, test/utils.test.js
This was the quick and dirty way to remove functionality here.
This needs to be revisited and cleaned up.
=> Stubbed out localDev param

src/deploy-actions.js, src/print-action-logs.js, src/undeploy-actions.js, src/utils.js, test/utils.test.js
- npm test
- via https://github.com/adobe/aio-cli-plugin-runtime/pull/385
- via https://github.com/adobe/aio-cli-plugin-app/pull/867
=> fix: support auth_handler

src/utils.js, test/utils.test.js
`require-adobe-auth` annotation was not working in v14 of the app plugin. This is because we rewrite an action definition to be behind a sequence with validators when we see this annotation but only for an allowlist of endpoints, and the deploy-service was not in this list. This annotation is in turn only supported by Adobe and not supported for a general OW instance. 
Technically aio-lib-runtime (and aio-cli-plugin-runtime) can be used on general OW servers so we should not generally apply this annotation.
I also re-factored the `require-adobe-auth` annotation tests -- 10 tests were in 1 function (not best practice to surface unit test failures because of a pre-emptive fail), I broke it out into 10 tests in a separate describe block. I also added three new tests for the 3 new endpoints. …
=> fix: deploying actions with require-adobe-auth not working with deploy-service
