adobe/aio-lib-runtime

- README.md
- types.d.ts
> apidocs for utils

- README.md
- src/utils.js
- test/utils.test.js
- types.d.ts
Fixes https://github.com/adobe/aio-cli-plugin-runtime/issues/111
> Util functions for [<param> takes precedence over <param-file> flags]

- src/build-actions.js
- test/build.actions.test.js
Relates to [https://github.com/adobe/aio-lib-ims/issues/55](https://github.com/adobe/aio-lib-ims/issues/55)
This flag will be used by aio-lib-ims to manage its dynamic imports.
manual tests
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ x] My code follows the code style of this project.
- [x ] I have read the **CONTRIBUTING** document.
- [ x] All new and existing tests passed.
> Added flag to indicate its an action build.

- package.json
- src/utils.js
- test/utils.test.js
Fixes https://github.com/adobe/aio-cli/issues/203
> Checking validity of node version in actions before deploying

- README.md
- package.json
- src/index.js
- src/print-action-logs.js
- src/utils.js
- test/jest.setup.js
- test/print.action.logs.test.js
- types.d.ts
New logs features/flags according to https://wiki.corp.adobe.com/display/AdobeCloudPlatform/Consolidation+of+logs+command+in+runtime+and+app+plugins
> logs filterable at namespace, manifest, package and action levels

- src/utils.js
- test/deploy.actions.test.js
- test/jest.setup.js
- test/utils.test.js
Reverts adobe/aio-lib-runtime#21
> Revert "Fix action urls when providing a custom apihost"

- package.json
- src/utils.js
- test/utils.test.js
> fix for #24: when package name is custom into branch 1.2.1

- src/build-actions.js
- src/deploy-actions.js
- test/deploy.actions.test.js
> Fix action filters for multi-pkg support

- docs/readme_template.md
- package.json
> add version script, update docs template

- src/build-actions.js
- src/deploy-actions.js
- src/utils.js
- test/build.actions.test.js
- test/deploy.actions.test.js
- test/utils.test.js
Fixes https://github.com/adobe/aio-cli-plugin-app/issues/380
Trying to build/deploy a package with no actions in it was throwing an error
```
✖ Building actions
TypeError: Cannot convert undefined or null to object
```
Fixed that
> Handle package with no actions

- .github/workflows/node.js.yml
- src/build-actions.js
- src/deploy-actions.js
- src/index.js
- src/undeploy-actions.js
- src/utils.js
- test/build.actions.test.js
- test/deploy.actions.test.js
- test/jest.setup.js
> fixes for most jsdoc warnings

- src/utils.js
- test/utils.test.js
fix: flag values that were numeric strings became numbers (JSON.parse). 
Fixes #47
> numeric strings became numbers

- package.json
- src/deploy-actions.js
- src/utils.js
- test/deploy.actions.test.js
- test/utils.test.js
> Support stage env for validators

- src/utils.js
- test/utils.test.js
Fixes https://github.com/adobe/aio-cli-plugin-app/issues/391
> Handling falsy values properly

- e2e/e2e.js
> default apihost for e2e

- package.json
- test/jest.setup.js
> Upgrade webpack for Node 14 support

- e2e/e2e.js
> Change for latest jest

- src/utils.js
- test/utils.test.js
> handle string values of true/false as json also

- .github/workflows/on-push-publish-to-npm.yml
> only run publish action if owner is adobe (#5)

- src/deploy-actions.js
- src/utils.js
- test/deploy.actions.test.js
- test/utils.test.js
> Stage validator in stage namespace

- src/utils.js
- test/utils.test.js
Fixes https://github.com/adobe/aio-cli-plugin-runtime/issues/234
> strip timestamps from empty logs too

- src/utils.js
- test/print.action.logs.test.js
Fixes https://github.com/adobe/aio-cli-plugin-runtime/issues/235
> Strip should not alter log msg order

- src/deploy-actions.js
- src/utils.js
- test/__fixtures__/deploy/basic_manifest.json
- test/__fixtures__/deploy/basic_manifest_res.json
- test/__fixtures__/deploy/pkgparam_manifest_res.json
- test/__fixtures__/deploy/pkgparam_manifest_res_multi.json
- test/deploy.actions.test.js
- test/utils.test.js
> Reference to a new headless validator

- .npmrc
- README.md
- package.json
- src/build-actions.js
- src/deploy-actions.js
- src/utils.js
- test/__fixtures__/deploy/basic_manifest.json
- test/__fixtures__/deploy/basic_manifest_res.json
- test/__fixtures__/deploy/pkgparam_manifest_res.json
- test/__fixtures__/deploy/pkgparam_manifest_res_multi.json
- test/build.actions.test.js
- test/deploy.actions.test.js
- test/utils.test.js
required for https://github.com/adobe/aio-cli-plugin-app/pull/417/
`Major version bump` because the validators have changed
> breaking change: new validators

- README.md
> Fix the initialization example

- e2e/.eslintrc.json
- e2e/e2e.js
This is to fix the e2e tests which were failing recently due to delayed or no response from Runtime activation logs API
> Handle case where Runtime returns 503 after 60 secs

- src/LogForwarding.js
- src/deploy-actions.js
- src/index.js
- src/print-action-logs.js
- src/undeploy-actions.js
- src/utils.js
- test/LogForwarding.test.js
> jsdoc fixes

- .github/workflows/prerelease.yml
This is a manual Github Actions workflow to publish a prerelease version of this library under a certain dist-tag.
> add prelease.yaml

- src/utils.js
> fix: turn windows path back into a globby pattern

- README.md
- src/utils.js
- test/utils.test.js
- types.d.ts
Dynamically get the supported runtimes from an Openwhisk api host
npm test
> feat: add getSupportedRuntimes util function

- README.md
- src/utils.js
- test/__fixtures__/deploy/basic_manifest_unsupported_kind.json
- test/utils.test.js
- types.d.ts
This is enabled in Adobe I/O Runtime but is not the default yet.
npm test
> feat: add `nodejs:16` supported runtime

- src/utils.js
- test/utils.test.js
fix for https://github.com/adobe/aio-cli-plugin-app/issues/603
> Fix: http localhost action urls

- package.json
- types.d.ts
Fixes #97 
npm run typings on Windows and Mac
> fix: ACNA-1971 - cannot release on Windows

- README.md
- docs/readme_template.md
- types.d.ts
> fix: README init example is incorrect

- src/utils.js
- test/utils.test.js
Static dummy commit to manually add the node 18 runtime.
> Add support for node 18

- package.json
- src/LogForwarding.js
- src/utils.js
- test/utils.test.js
Closes #121
- npm i --package-lock --package-lock-only
- npm test
> fix: update deps to fix peer dependencies

- test/print.action.logs.test.js
> Fix test failure

- e2e/e2e.js
See https://github.com/adobe/aio-lib-runtime/commit/ab1aec9959b2069d91addb9610556c2e6ac4603f
> fix: e2e test failure due to removal of symlinks

- e2e/e2e.js
- e2e/jest.setup.js
- test/__fixtures__/sample-app/manifest.yml
> fix: ACNA-2078 - add api url e2e test

- e2e/e2e.js
- test/build.actions.test.js
> fix: ACNA-2479 - e2e test should be a unit test

- package.json
> chore: update openwhisk dep to 3.21.8 ( updates needle )

- src/utils.js
- test/utils.test.js
> fix: ACNA-2963 - an action with annotation web-export: raw should be considered a web action in getActionUrl

- src/deploy-actions.js
- test/.eslintrc.json
- test/__fixtures__/sample-app-duplicate/actions/action.js
- test/__fixtures__/sample-app-duplicate/manifest.yml
- test/__fixtures__/sample-app-duplicate/package.json
- test/deploy.actions.test.js
- test/jest.setup.js
Fixes https://github.com/adobe/aio-cli/issues/614
npm test
> fix: ACNA-2967 - web actions and web sequences with the same name can be deployed, web action implementation is unreachable

- .gitignore
- e2e/e2e.js
- test/build.actions.test.js
- test/utils.test.js
- types.d.ts
> Fix e2e tests that were failing, some cleanup

- src/utils.js
- test/utils.test.js
bug fix surfaced using e2e tests
- npm run e2e
> fix: processing and assigning an action's annotations when there are none

- package.json
Updating eslint-config-aio-lib-config and peer deps
[ACNA-3335](https://jira.corp.adobe.com/browse/ACNA-3335)
- `npm install && npm run lint && npm test`
> ACNA-3335 | Updating eslint-config-aio-lib-config and peer deps

- package.json
- test/build.actions.test.js
> fix: TypeError: fs.opendirSync is not a function

- src/build-actions.js
> Hash full action path

- src/deploy-actions.js
- src/print-action-logs.js
- src/undeploy-actions.js
- test/deploy.actions.test.js
- test/print.action.logs.test.js
- test/undeploy.actions.test.js
- Added auth_handler to openwhisk for the `bearer token` authorisation
- Added condition check for auth_handler
[ACNA-3659](https://jira.corp.adobe.com/browse/ACNA-3659)
[ACNA-3602](https://jira.corp.adobe.com/browse/ACNA-3602)
- Unit test [🟢]
- Manual API Testing Completed [🟢]
> feat: ACNA-3659 | Add auth_handler to OW
